### ISSUE TITLE
脚本执行错误No such file or directory

### ISSUE THREAD

**Issue by TengJW** [vveg26/sing-box-reality-hysteria2#10]
[root@sweet-unicorn-2 ~]# bash <(curl -fsSL https://github.com/vveg26/sing-box-reality-hysteria2/raw/main/reality_hy2_ws.sh)
sing-reality-hy2-wss-box by 绵阿羊

Architecture: x86_64
Latest version: 1.6.0-beta.1
/dev/fd/63: line 99: tar: command not found
mv: cannot stat '/root/sing-box-1.6.0-beta.1-linux-amd64/sing-box': No such file or directory
rm: cannot remove '/root/sing-box-1.6.0-beta.1-linux-amd64': No such file or directory
chown: cannot access '/root/sbox/sing-box': No such file or directory
chmod: cannot access '/root/sbox/sing-box': No such file or directory

开始配置Reality

自动生成基本参数

/dev/fd/63: line 731: /root/sbox/sing-box: No such file or directory
Key pair生成完成

/dev/fd/63: line 743: /root/sbox/sing-box: No such file or directory
/dev/fd/63: line 744: /root/sbox/sing-box: No such file or directory
uuid和短id 生成完成

**Comment by TengJW** [comment]
补充：就算自行上传sing-box，脚本一执行，也会被删掉

**Comment by vveg26** [comment]
系统没安装tar命令
