### ISSUE TITLE
无法使用已经解析的域名(自动优选IP,并解析到域名)，只能是具体IP数字

### ISSUE THREAD

**Issue by ainp** [vveg26/sing-box-reality-hysteria2#12]
你好，vmess 客户端clash meta的server: 只能填写具体的IP,只要填写已经解析的域名就无法使用（自动优选IP 并解析到域名）。

**Comment by vveg26** [comment]
我没有用过自动优选IP并解析到域名，但是我这边手动将优选ip解析到域名，测试了下是可用的
![clash配置](https://img.mareep.net/blog/2023/10/1ce12500c5b1ad2ffc2bdf8cbcfdc88b.jpg)
![a](https://img.mareep.net/blog/2023/10/bb547266a232d2c8eba9546e26219c9f.jpg)
![cname](https://img.mareep.net/blog/2023/10/383a28d91ac4ebc3bca478a4570f1e5f.jpg)

**Comment by ainp** [comment]
确实可以了，谢谢您的及时回复，辛苦了（昨晚一直不行，不知为何）

**Comment by ainp** [comment]
![截屏2023-10-26 下午7 47 09](https://github.com/vveg26/sing-box-reality-hysteria2/assets/9693302/78a26ce6-04d2-42db-88ff-00e0833252d7)
![image](https://github.com/vveg26/sing-box-reality-hysteria2/assets/9693302/02920031-e0b4-45a7-ad4a-aa3e6b55a7ad)

又试了几次，有时候还是不行，发现可能不稳定

**Comment by ainp** [comment]
我发现可能和您的脚本和程序无关，有可能是晚上的优选IP会很快失效有关，只要出现下面的情况就不行![image](https://github.com/vveg26/sing-box-reality-hysteria2/assets/9693302/3e2c3918-58a8-47a4-8e62-88b5d67fb2e5)

**Comment by ainp** [comment]
不好意思，继续报告问题，即时不做任何改变(系统也重置了)，直接使用你提供的配置clash-meta客户端，vmess+ws今天都无法使用(clash verge/clash for windows）。而 reality 和 hysteraia2 都正常。（我自己使用x-ui 搭建的vmess+ws 都正常).感觉好怪。

**Comment by ainp** [comment]
我截图了clash verge 的日志：希望能有用![image](https://github.com/vveg26/sing-box-reality-hysteria2/assets/9693302/61fc02bc-6691-4e87-b6d5-e569439d337d)

**Comment by vveg26** [comment]
理论上应该和普通的vmessws没啥区别，我这个是用argo搞了个临时隧道搭配vmess。你这看起来是连不上speed.cloudflare.com，你自己搭建的vmess+ws有用优选ip吗，是同一个优选ip在x-ui可以使用而在我的脚本上无法使用吗

**Comment by ainp** [comment]
你好，我用了您提供的优选IP也试了，仍是非常的不稳定。我网上查了一些资料，可能和墙相关，因为你提供的伪装网站，并不是真正的网站，是不是被墙探测到了，是不是需要用nginx 搭一个反查网站，以躲过墙（小白纯属猜测）![image](https://github.com/vveg26/sing-box-reality-hysteria2/assets/9693302/7f19a1c2-1d0e-49f2-aa8d-9c936e8fdb0f)

**Comment by ainp** [comment]
我在想你这一直正常，是不是你用的客户端和我不一样（我用clash verge 和clash for windows).另外，我自己搭了一个nginx 反代网站，得到的结果如下：
Error 1033 Ray ID: 81d81859f12407ae • 2023-10-29 02:47:39 UTC
Argo Tunnel error
What happened?
You've requested a page on a website (sector-seventh-min-circles.trycloudflare.com) that is on the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. The host (sector-seventh-min-circles.trycloudflare.com) is configured as an Argo Tunnel, and Cloudflare is currently unable to resolve it.


What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Ensure that cloudflared is running and can reach the network. You may wish to enable [load balancing](https://developers.cloudflare.com/argo-tunnel/reference/load-balancing/) for your tunnel.
