### ISSUE TITLE
只要使用脚本更新参数，就无法再启动了，一直报single-box配置错误。

### ISSUE THREAD

**Issue by feidaodu** [vveg26/sing-box-reality-hysteria2#15]
如题，我是今天按装的。。beta.sh 不是install.sh 搞完后，我想试试能修改啥，一修改后，一路回车，其实啥都没有改，但是改完。。就无法启动了，只有重装。。

另外，脚本能否支持多用户？虽然我可以自己该SB的配置文件，实际这个功能，但是还是跟您的脚 本会有冲突。。最好的就是您的脚 本能本身支持。

**Comment by vveg26** [comment]
第一个bug修好了
