### ISSUE TITLE
看了视频, 给你两个建议, 可以做到重启VPS以后全自动

### ISSUE THREAD

**Issue by crazypeace** [vveg26/sing-box-reality-hysteria2#2]
给你几个建议
1. 重启VPS之后, 可以让系统自动执行某个命令. 
就是说执行你的这个6的执行.
参考: https://zelikk.blogspot.com/2022/11/telegram-keyword-alert-tgbot-hax-us.html
crontab -e 的用法

2. 重新执行6以后, server name会变化.
你可以用cloudflare的API, 设置一个CNAME, 这样你最终生成的VMESS配置就不用动了, 你的使用者不需要任何操作. 更加适合小白.

**Comment by vveg26** [comment]
谢谢。我准备给6加个开机自启。第二种方式没有了解过，有资料参考一下吗

**Comment by crazypeace** [comment]
https://github.com/XIU2/CloudflareSpeedTest/issues/40#issuecomment-767439136

**Comment by crazypeace** [comment]
提醒你, CLOUDFLARE的API对于免费域名是不让用的. 比如.cf . tk. 这种域名.

**Comment by vveg26** [comment]
谢谢，简单看了下，涨姿势了。但是这样应该需要自己有一个域名了，如果把自己的域名用来同步argo生成的临时域名，不如直接用自己的域名申请证书，然后再用他的方法将自己的域名绑定一下优选出的最快ip来得方便些。

**Comment by crazypeace** [comment]
可能吧, 你试试?
