### ISSUE TITLE
关于argo 隧道 在vps 重启或者其他操作后，不正常的问题

### ISSUE THREAD

**Issue by ainp** [vveg26/sing-box-reality-hysteria2#20]
博主，你好！
      我在其他地方有看到VPS 重启后，有可能Argo 隧道会有变化，原来生成的临时的SNI 会不同，是真的吗？会不会这个就是有时候。会有问题的原因

**Comment by vveg26** [comment]
临时隧道重启域名会变化，其他操作只要不把argo关了，域名一般都不会有变化。但是我觉得和优选ip ddns用不了可能关系不大，f佬不是有个argox吗，你可以试试看
