### ISSUE TITLE
希望加上代理转发的功能

### ISSUE THREAD

**Issue by akaagiao1** [vveg26/sing-box-reality-hysteria2#21]
大佬发现你的脚本很好用能满足我们基本的需求能不能加上简单的代理转发功能，以完善流媒体分流或者解决油管送中和解锁openai ，感激不尽，落地机感觉常见的ss协议或者vmess加 tcp或者ws就行

**Comment by vveg26** [comment]
转发再看吧，新加了个warp来解锁，根据需求自己改改。 https://github.com/vveg26/sing-box-reality-hysteria2#1210更新
