### ISSUE TITLE
Dec.6 脚本新建 报错

### ISSUE THREAD

**Issue by datouq** [vveg26/sing-box-reality-hysteria2#23]
ERROR [97766868 164ms] inbound/vless[vless-in]: process connection from 101.82.xxx.xx:43023: flow mismatch: expected xtls-rprx-vision, but got none
脚本唯一输入改的地方是吧bing.com 改成了mianyang 推荐的日本动漫网站了

**Comment by datouq** [comment]
root@ip-172-26-36-72:~# journalctl -u sing-box -o cat -e
+0000 2023-12-06 12:17:07 INFO [3811669367 0ms] inbound/vless[vless-in]: inbound connection from 66.160.133.238:44938
+0000 2023-12-06 12:17:29 ERROR [3811669367 21.94s] inbound/vless[vless-in]: process connection from 66.160.133.238:44938: REALITY: processed invalid >
+0000 2023-12-06 12:23:40 INFO [478866409 0ms] inbound/vless[vless-in]: inbound connection from 206.81.12.175:62074
+0000 2023-12-06 12:23:40 ERROR [478866409 171ms] inbound/vless[vless-in]: process connection from 206.81.12.175:62074: REALITY: processed invalid con>
+0000 2023-12-06 12:34:38 INFO [3315226744 0ms] inbound/vless[vless-in]: inbound connection from 91.92.250.14:59700
+0000 2023-12-06 12:34:41 ERROR [3315226744 2.24s] inbound/vless[vless-in]: process connection from 91.92.250.14:59700: REALITY: processed invalid con>
+0000 2023-12-06 12:37:44 INFO [1438446029 0ms] inbound/vless[vless-in]: inbound connection from 139.162.84.205:61000
+0000 2023-12-06 12:38:15 ERROR [1438446029 31.35s] inbound/vless[vless-in]: process connection from 139.162.84.205:61000: REALITY: processed invalid >
+0000 2023-12-06 12:57:22 INFO [2803499015 0ms] inbound/vless[vless-in]: inbound connection from 66.160.133.233:46635
+0000 2023-12-06 12:57:44 ERROR [2803499015 22.0s] inbound/vless[vless-in]: process connection from 66.160.133.233:46635: REALITY: processed invalid c>
+0000 2023-12-06 13:05:39 INFO [3526314724 0ms] inbound/vless[vless-in]: inbound connection from 106.75.172.22:45038
+0000 2023-12-06 13:05:40 ERROR [3526314724 259ms] inbound/vle

**Comment by vveg26** [comment]
> ERROR [97766868 164ms] inbound/vless[vless-in]: process connection from 101.82.xxx.xx:43023: flow mismatch: expected xtls-rprx-vision, but got none 脚本唯一输入改的地方是吧bing.com 改成了mianyang 推荐的日本动漫网站了

1. 猜测大概率客户端的问题，用的什么客户端，有没有开vision。
2. 你改的是自签的bing.com，应用在hysteria2上，改什么都无所谓，和vision reality没有什么关联。

**Comment by jackszb** [comment]
老大3合1脚本好像没有完成吧，很多选项都是空白啊，不过在测试版客户端里面可以使用。

**Comment by vveg26** [comment]
> 老大3合1脚本好像没有完成吧，很多选项都是空白啊，不过在测试版客户端里面可以使用。

哪些选项空白呢，能否具体一点，应该都实现了

**Comment by jackszb** [comment]
另外老大能不能把你那个tcp-brutal那个替代这个脚本里面的reality,直觉tcp-brutal打开网页更快，vmess其实用处不大，目前看HY2和tcp-brutal-reality这两个搞一个脚本就完美了。感谢老大辛苦付出。

**Comment by jackszb** [comment]
老大，brutal reality vision reality hysteria2三合一脚本报错，1.8.0.sing-box bata苹果电脑客户端，报错如下：(packet-tunnel) error: create service: decode config: outbounds[0]: json: cannot unmarshal string into Go value of type option._Outbound

**Comment by jackszb** [comment]
补充一下我刚刚升级了系统，m1 air，重新安装了sing-box测试版

**Comment by vveg26** [comment]
> 补充一下我刚刚升级了系统，m1 air，重新安装了sing-box测试版

待会修

**Comment by vveg26** [comment]
> 补充一下我刚刚升级了系统，m1 air，重新安装了sing-box测试版

修好了，复制粘贴的时候漏掉了一些东西

**Comment by jackszb** [comment]
好的，感谢，我下午试试看。

Mareep ***@***.***>于2023年12月12日 周二13:28写道：

**Comment by jackszb** [comment]
老大，测试了一下这个脚本很稳，希望下个版本看能不能增加你脚本更新的选项？感谢！

**Comment by vveg26** [comment]
> 老大，测试了一下这个脚本很稳，希望下个版本看能不能增加你脚本更新的选项？感谢！

输入mianyang会自动拉取最新脚本

**Comment by jackszb** [comment]
好的，明白了！谢谢

Mareep ***@***.***>于2023年12月12日 周二23:12写道：

**Comment by jackszb** [comment]
老大，这两天测试了你这个页面的全部的脚本，分别用sing-box1.7.0和1.8.0测试，发现tcp-brutal-reality单独脚本延迟最低，其他多合一脚本延迟明显比较高，并且有偶尔断流现象发生。按道理多合一脚本里面tcp-brutal-reality协议应该一样吧，但是延迟明显高了不少，是否多合一之后会增加延迟？并且hy2协议速度大幅不如预期，我平时hy2单独搭建的速度在15万左右，而在你的脚本里面最高3万，我在两台vps上面测试的结果都如此。以上都是反复多次的测试结果，供你参考。另外老大有空的时候能否把tcp-brutal-reality单独脚本加上warp分流功能，非常感谢！

**Comment by vveg26** [comment]
> 老大，这两天测试了你这个页面的全部的脚本，分别用sing-box1.7.0和1.8.0测试，发现tcp-brutal-reality单独脚本延迟最低，其他多合一脚本延迟明显比较高，并且有偶尔断流现象发生。按道理多合一脚本里面tcp-brutal-reality协议应该一样吧，但是延迟明显高了不少，是否多合一之后会增加延迟？并且hy2协议速度大幅不如预期，我平时hy2单独搭建的速度在15万左右，而在你的脚本里面最高3万，我在两台vps上面测试的结果都如此。以上都是反复多次的测试结果，供你参考。另外老大有空的时候能否把tcp-brutal-reality单独脚本加上warp分流功能，非常感谢！

1. hy2的singbox客户端配置文件的话，我singbox默认是设置了上传下载100mbps，你可以根据自己的上传下载速度进行设置，或者直接删除上传下载用hy的bbr。
不知道你平常是用hy2的bbr还是brutal。

2. 多合一和单独的应该没啥区别吧，我有空再看看，我应该就加个了个sniff嗅探分流用，这个应该不会有很大影响吧

**Comment by jackszb** [comment]
我家电信带宽100M，我另外一台vps搭建Hy2的脚本使用的是小破站的一键脚本，平时跑就是15万，三台vps我都测试过，都是这个数字。你的tcp-brutal-reality一键脚本打开网页速度特别快，这是我玩vps以来觉得最快速度了，即使跑youtube3万左右，还是觉得这个脚本很不错，所以希望加上分流功能。谢谢！

Mareep ***@***.***>于2023年12月14日 周四11:38写道：

**Comment by vveg26** [comment]
> 我家电信带宽100M，我另外一台vps搭建Hy2的脚本使用的是小破站的一键脚本，平时跑就是15万，三台vps我都测试过，都是这个数字。你的tcp-brutal-reality一键脚本打开网页速度特别快，这是我玩vps以来觉得最快速度了，即使跑youtube3万左右，还是觉得这个脚本很不错，所以希望加上分流功能。谢谢！

我有空看看吧，打开网页速度快很大程度是多路复用的功效，你用grpc应该也有这效果

**Comment by jackszb** [comment]
老大，我测试tcp-brutai-reality一键脚本里面的分流选择之后无反应，是直接返回重新选择了吗？这个操作逻辑是不是有点奇怪，个人观点供你参考，脚本非常棒！感谢老大为我们小白辛苦付出！

**Comment by vveg26** [comment]
> 老大，我测试tcp-brutai-reality一键脚本里面的分流选择之后无反应，是直接返回重新选择了吗？这个操作逻辑是不是有点奇怪，个人观点供你参考，脚本非常棒！感谢老大为我们小白辛苦付出！

改了逻辑

**Comment by jackszb** [comment]
感谢老大！

**Comment by jackszb** [comment]
老大，brutal reality vision reality hysteria2三合一脚本报错了（sing-box 1.7.6),报错如下
Service Error

(packet-tunnel) error: create service: decode config: invalid character ',' looking for beginning of value: row 161, column 22

**Comment by vveg26** [comment]
我这边1.7.6可以正常使用，你检查一下你配置文件161行附近

**Comment by jackszb** [comment]
好的，感谢！

Mareep ***@***.***>于2023年12月23日 周六22:35写道：

**Comment by jackszb** [comment]
可以使用了。请问老大一个问题，当开启了端口跳跃时候，几分钟就断流一下正常吗？是不是因为在换端口？如果这样的话，不如不开启吧？

**Comment by vveg26** [comment]
> 可以使用了。请问老大一个问题，当开启了端口跳跃时候，几分钟就断流一下正常吗？是不是因为在换端口？如果这样的话，不如不开启吧？

我没用过端口跳跃，但是和端口跳跃可能无关吧。我记得官方客户端默认是30s一跳，而且quic连接迁移应该不会断流的

**Comment by jackszb** [comment]
谢谢回答。我关闭了端口跳跃就正常了，看来还是这个技术不成熟。

Mareep ***@***.***>于2023年12月24日 周日14:17写道：

**Comment by SLEEPY5AD0** [comment]
请问一下有一键卸载脚本吗 或是怎么卸载掉这些呢

**Comment by vveg26** [comment]
> 请问一下有一键卸载脚本吗 或是怎么卸载掉这些呢

输入mianyang

**Comment by jackszb** [comment]
老大看看tcp-brutal-reality一键脚本吧，好像不能使用了，看得到流量但是不能使用了，重复装了两遍都一样。我怀疑是不是目标网站不能用了，尝试更换目标网站脚本一直说我选择的目标网站不行，我记得之前可以更换的。我使用sing-box1.7.6版本。

**Comment by jackszb** [comment]
抱歉，是我系统的原因，我重装系统之后又可以了

**Comment by jackszb** [comment]
老大，tcp-brutal reality节点好像都不通了，包括最新测试版

**Comment by jackszb** [comment]
补充一下vps是最新的Debian 12.4

**Comment by jackszb** [comment]
老大新年好！感谢老大出的优质一键脚本！另外老大脚本里面分流和流媒体解锁种类非常多，我等小白不知道怎么选择，请老大做一期视频仔细说明一下每种选项的意义，推荐一种最优的方法，现在主要需求其实只有Netflix和chatgpt解锁，谢谢

**Comment by jackszb** [comment]
补充一下，希望只有这两个解锁，访问其他网站速度不影响
