### ISSUE TITLE
hysteria2有问题，看视频一会儿就会超时

### ISSUE THREAD

**Issue by wu278909653** [vveg26/sing-box-reality-hysteria2#25]
hysteria2在路由的passwall端有问题，看视频一会儿就会超时断网，在vps输入“mianyang”会报以下错误
curl: (6) Could not resolve host: github.com

**Comment by wu278909653** [comment]
hysteria2有问题，看视频一会儿就会超时断网，在vps输入“mianyang”会报以下错误，一两分钟之后才能恢复然后循环。
curl: (6) Could not resolve host: github.com

**Comment by wu278909653** [comment]
![Uploading err.png…]()

**Comment by wu278909653** [comment]
![err](https://github.com/vveg26/sing-box-reality-hysteria2/assets/106575252/2ad27d4f-2a92-4f4e-835f-92dec4070d9c)

**Comment by vveg26** [comment]
> ![err](https://github.com/vveg26/sing-box-reality-hysteria2/assets/106575252/2ad27d4f-2a92-4f4e-835f-92dec4070d9c)
> 
> 

看起来是vps的dns解析不到github的域名
