### ISSUE TITLE
warp切换不生效

### ISSUE THREAD

**Issue by Pacio** [vveg26/sing-box-reality-hysteria2#26]
![image](https://github.com/vveg26/sing-box-reality-hysteria2/assets/6836705/dc29030b-8b71-4b1e-be14-16c1b1be41ff)
使用版本:[brutal-reality-hysteria.sh](https://github.com/vveg26/sing-box-reality-hysteria2/blob/main/brutal-reality-hysteria.sh)

**Comment by vveg26** [comment]
jq没装上

debian/ubuntu

```
apt install jq
```

centos

```
yum install jq
```
