### ISSUE TITLE
sing-box-reality-brutal"	不可以访问

### ISSUE THREAD

**Issue by htale** [vveg26/sing-box-reality-hysteria2#27]
bash <(curl -fsSL https://github.com/vveg26/sing-box-reality-hysteria2/raw/main/brutal-reality-hysteria.sh)
三合一
里面的brutal-reality-hysteria这个节点没有生效。试了好几个vps都是一样
        "sing-box-reality", 可以访问
        "sing-box-hy2", 可以访问
        "sing-box-reality-brutal"	不可以访问

**Comment by vveg26** [comment]
可以检查下tcp brutal模块是否成功安装
