### ISSUE TITLE
和fscarmen的argox脚本合并一下是不是协议就齐全了?

### ISSUE THREAD

**Issue by crazypeace** [vveg26/sing-box-reality-hysteria2#29]
https://github.com/fscarmen/argox
里面有 trojan, vless, ss.

合并一下是不是协议就齐全了?

**Comment by vveg26** [comment]
> https://github.com/fscarmen/argox
> 
> 里面有 trojan, vless, ss.
> 
> 
> 
> 合并一下是不是协议就齐全了?

有空我看看这个
