### ISSUE TITLE
脚本里面分流和流媒体解锁种类非常多，如何选择

### ISSUE THREAD

**Issue by vveg26** [vveg26/sing-box-reality-hysteria2#32]
老大新年好！感谢老大出的优质一键脚本！另外老大脚本里面分流和流媒体解锁种类非常多，我等小白不知道怎么选择，请老大做一期视频仔细说明一下每种选项的意义，推荐一种最优的方法，现在主要需求其实只有Netflix和chatgpt解锁，谢谢

_Originally posted by @jackszb in https://github.com/vveg26/sing-box-reality-hysteria2/issues/23#issuecomment-1873710334_

**Comment by vveg26** [comment]
新年好，默认的流媒体解锁就是用warp的优先ipv6解锁openai和奈飞。
新加的任意门那个就是**xray的任意门的singbox版**，一般用来中转或者落地机vps解锁用的，一般人基本用不到，然后这个东西还要稍微修改一下

**Comment by jackszb** [comment]
好的！谢谢老大！

Mareep ***@***.***>于2024年1月2日 周二16:41写道：

**Comment by jackszb** [comment]
老大，tcp-brutal reality一键脚本Netflix非自制剧解锁好像失效了，有空请看看

**Comment by jackszb** [comment]
还补充一个问题，苹果手机端使用该脚本之后，很多信息收不到了，是不是规则屏蔽了国内网站？

**Comment by vveg26** [comment]
1. 第一个盲猜是注册到的warp节点解锁不了奈飞，你可以访问一下[ipaddress.my](https://ipaddress.my),看看是不是warp的ipv6，如果是的话，大概率就是这个问题。
解决办法可以**输入mianyang，然后输入6，再输入5，删除解锁，然后再输入mianyang，输入6重新生成一次**，毕竟有的warp节点解锁不了奈飞。如果还不行就再重复上述操作几次，刷到能解锁的节点就可以一直用了。
2. 第二个，没有屏蔽国内网站，你用的是singbox客户端吗，有可能我客户端分流搞太简单了，有空改一下分流

**Comment by jackszb** [comment]
第一个问题我验证过的，确实是失效了，原因不明。第二个分流问题，我也反复验证了，我有其他方法搭建的节点，使用你的方法节点后，转化其他节点，马上收到很多信息，都是之前的消息。我是关闭手机信号在Wi-Fi下测试的结果，所以就是国内网站消息收不到。谢谢老大！

Mareep ***@***.***>于2024年1月3日 周三00:11写道：

**Comment by vveg26** [comment]
能否提供一下其他节点的客户端配置文件，因为现在国内分流默认走的是geosite-cn，如果你用的是苹果手机，他的推送机制应该是走得苹果服务器，然后geo可能没有囊括这些导致消息接受走的是你的翻墙流量。

**Comment by vveg26** [comment]
那大概就是singbox的客户端配置文件的icloud分流默认走的是你vps的流量，然后走不通，如果你复制我的分享链接到小火箭里面应该也不会出现app store打不开的问题，**下次更新改下客户端的分流**

**Comment by jackszb** [comment]
谢谢老大！

Mareep ***@***.***>于2024年1月5日 周五23:05写道：
