### ISSUE TITLE
三合一脚本warp解锁奈飞貌似失效

### ISSUE THREAD

**Issue by qveritas** [vveg26/sing-box-reality-hysteria2#34]
大佬好，使用三合一脚本的warp分流解锁时，奈飞仍然只能观看自制剧，无法观看非自制剧。我尝试过重新安装将脚本更新到最新，也warp解锁也刷了五六次，依旧无法解锁非自制剧观看。请问大佬我是需要多刷几次warp就能解锁么？还是可能脚本出现了bug？

**Comment by vveg26** [comment]
待会测一下，要是不行的话，可能是现在不太好刷，那我就默认搞一个能解锁的warp节点放上去看看，然后刷warp的功能留着
