### ISSUE TITLE
更新脚本后hy2端口跳跃开启检测失效了

### ISSUE THREAD

**Issue by 69Billyham** [vveg26/sing-box-reality-hysteria2#36]
![image](https://github.com/vveg26/sing-box-reality-hysteria2/assets/140883647/cbaf3151-efcb-40fa-985e-f11bca230b2c)

先赞一个👍大佬脚本，warp分流设置好用！有时间可以修复这个bug。
同时加个私心希望大佬能添加一个Argox的Vless选项就更完美了

**Comment by vveg26** [comment]
bug修复了
然后关于argox，我浏览了一下脚本，他是用xray的回落根据不同的path去将流量发给不同的协议，但是singbox的作者已经把回落给砍了，导致无法优雅的实现argox的功能。
~~然后个人愚见，argox的大部分协议都大同小异，例如vless/vmess/trojan  ws argo和三合一的vmess ws argo没有本质区别~~ 当然argox设计还是比较巧妙的。
