### ISSUE TITLE
大佬，非常感谢你的辛勤付出，帮助了我这样的小白！有个小问题想请教

### ISSUE THREAD

**Issue by tgssaa** [vveg26/sing-box-reality-hysteria2#37]
请问，脚本自动生成密码，自己想修改，该如何修改？

**Comment by vveg26** [comment]
脚本暂时没有加入修改密码的选项，可以手动在配置文件中修改
```bash
nano /root/sbox/sbconfig_server.json
```
然后修改hysteria2入站的密码部分即可
<img width="874" alt="image" src="https://github.com/vveg26/sing-box-reality-hysteria2/assets/62206240/82adc003-009b-4faf-b666-a6873f48d6a7">

**Comment by tgssaa** [comment]
非常感谢大佬的帮助！！！
